### ISSUE TITLE
issue during deployment

### ISSUE THREAD

**Issue by havok-time** [capesstack/capes#36]
When deploying CAPES via the how-to documentation, the deployment seemed to go through smoothly - however once I tried to navigate to thehive, I was unable to login and received an error: 

>ElasticSearch Cluster is Unreachable

after running 

>sudo systemctl status elasticsearch.service

I received this output:

>elasticsearch.service - Elasticsearch
>  Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendo                                                                                                                                                             >r preset: disabled)
> Active: failed (Result: signal) since Fri 2017-09-22 15:36:33 UTC; 52min ago
>    Docs: http://www.elastic.co
> Process: 27127 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_D                                                                                                                                                            > IR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.path.data                                                                                                                                                             > =${DATA_DIR} -Edefault.path.conf=${CONF_DIR} (code=killed, signal=KILL)
> Process: 27125 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd                                                                                                                                                             > -pre-exec (code=exited, status=0/SUCCESS)
> Main PID: 27127 (code=killed, signal=KILL)
>
> Sep 22 15:34:50 CAPES systemd[1]: Starting Elasticsearch...
> Sep 22 15:34:50 CAPES systemd[1]: Started Elasticsearch.
> Sep 22 15:34:50 CAPES elasticsearch[27127]: OpenJDK 64-Bit Server VM warning...N
> Sep 22 15:36:33 CAPES systemd[1]: elasticsearch.service: main process exite...LL
> Sep 22 15:36:33 CAPES systemd[1]: Unit elasticsearch.service entered failed...e.
> Sep 22 15:36:33 CAPES systemd[1]: elasticsearch.service failed.

I wasn't sure if I was doing something incorrect during deployment, or if something went wrong with elasticsearch.

**Comment by peasead** [comment]
@havok-time I'm unable to duplicate this on CentOS 7.4.1708 (Core).

Can you share your version of CentOS (`cat /etc/redhat-release`) and your install steps?

**Comment by havok-time** [comment]
I used CentOS 7.4.1708 (Minimal). I installed using the Build Your OS guide
within the CAPES documentation first, then

git clone https://github.com/capesstack/capes.git
# if you're feeling adventurous git clone -b devel
https://github.com/capesstack/capes.git
cd capes
sudo sh deploy_capes.sh

it appeared to go through without an issue - I only ran into an issue when
I tried to access thehive.

let me know if you need more details/info.

**Comment by peasead** [comment]
So you gave it at least 4 GB RAM?

**Comment by havok-time** [comment]
16GB

**Comment by peasead** [comment]
@havok-time have you been able to identify why Elasticsearch wasn't starting or has this been resolved?

**Comment by havok-time** [comment]
It appears this was a time issue, when I rebuilt CAPES on a new VM, the
same problem occurred, but when I tried again a couple minutes later it
worked just fine, so I'm thinking maybe Elasticserach hadn't finished
starting when I first tried to get to TheHive.

**Comment by peasead** [comment]
Thanks for the update @havok-time
