### ISSUE TITLE
Gogs Database Auth Fails

### ISSUE THREAD

**Issue by ikehoff** [capesstack/capes#46]
Hello, 

I've followed the Build, Operate, Maintain documentation and I cannot get Gogs to accept the database connection. I used the capes_deploy script and set a random password for MySQL at the beginning of this script. At the end of the script I copied the password output for MySQL and paste it into the password field of the Gogs setup page. I also followed the rest of the BOM and changed the Domain and App URL to the IP address of the server. Finally, I changed the root user to be gogs. 

The error I get is as follows:
Database setting is not correct: Error 1045: Access denied for user 'gogs'@'localhost' (using password: YES)

I should note: This is the second time this has happened to me with fresh deploys. I am using CentOS 7 (Build 1708) Minimal ISO.

**Comment by peasead** [comment]
Thanks @ikehoff 

Let me take a look. My guess is that the documentation on the Gogs side is missing a step.

I built it this weekend but did it from memory vs. from the docs. I'll have an answer to you tonight.

**Comment by peasead** [comment]
@ikehoff I am unable to reproduce your exact issue, but this likely has to do with the build of GoGS that was released on November 22, `0.11.34` .

I'm working on the issue. I'll follow up ASAP.

**Comment by ikehoff** [comment]
Thanks for the update!

**Comment by peasead** [comment]
@ikehoff 

I have been able to reproduce your issue, but only when using the wrong passphrase. Perhaps during the installation, you may have used a trailing or preceding whitespace?

Maybe try to reset the passphrase for the `gogs` user to something manually vs. using the script?
```
mysql -u root -p
SET PASSWORD FOR gogs'@'localhost' = PASSWORD('new-password-here');
quit
```
See if maybe that helps you past the authentication issue. Please let me know.

That said, you're going to run into another issue regarding an update to GoGS, but that issue comes after auth is successful #48 .

**Comment by ikehoff** [comment]
@peasead I ended up getting this error too and still couldn't login. So I'm not crazy.... :)

**Comment by peasead** [comment]
Okay @ikehoff, I have dropped GoGS and went to Gitea, which is a community managed fork of GoGS.

It seems to work the same and doesn't have the database issues that we were seeing with GoGS.

Let me know if this works for you.

**Comment by ikehoff** [comment]
Redeploying now....
Works! Good job!
