### ISSUE TITLE
Wrong folder specified for TheHive application.conf file in README.md

### ISSUE THREAD

**Issue by infosecjulia** [capesstack/capes#75]
Under Post Installation instructions for TheHive it reads:
"Open /opt/thehive/application.conf and go to the very bottom of the document and add key = <your-api-key> to the CORTEX-SERVER-ID section (your-IP-address should already be populated). The API key is the one you created above in Cortex."

However application.conf resides in /etc/thehive/, not /opt/thehive.

**Comment by peasead** [comment]
Thanks!

If you do a PR, you can get contributor status or I can fix it. 

Just making sure you get credit where credit is due.

**Comment by jcuaderes** [comment]
Hi Andrew,

Thanks! I’m not at a computer now but I’ll do it when I am. Btw, love Capes. Actively using it in projects!

Cheers,
Julia

**Comment by peasead** [comment]
This was completed with PR #76
