### ISSUE TITLE
Manual alerting to the Hive

### ISSUE THREAD

**Issue by Deastrom** [capesstack/capes#93]
A workflow that I see occurring in some exercises is the result of a common situation.  
The incident response team does not own the network.  Rules for alerting haven't been setup or haven't been tuned yet.  
An operator is placed on each analyst box, packet sniffer, log aggregate, critical systems, etc...  One of these operators sees something and announces it to the room.  Chaos ensues.
To remediate this confusion the team starts to use chat, or a marker board, or something, to start tracking the incident.
Incident tracking should be done by the Hive, but since the announcement didn't come through in the form of an alert, the Hive is forgotten.
I'm thinking if a guy had a way to create an alert manually and ship it to the Hive, then the use of the Hive will feel more natural.
Please build a form into your front page that creates alerts for the Hive.

**Comment by peasead** [comment]
Thanks for the description and background of your use-case.

To speed up the incident creation process, you can create templates that have a lot of things pre-populated. I have included a [configuration file](https://github.com/capesstack/capes/blob/master/thehive/capes-config.conf) for the use of TheHive that has several templates to get you started. Feel free to update and modify to fit your needs.

TheHive has an API (documented [here](https://github.com/TheHive-Project/TheHive4py) and [here](https://github.com/TheHive-Project/TheHiveDocs/tree/master/api
)) that you can use to accomplish this if you're looking for a way to create a custom web front-end. 

All that said, this seems like more of a niche case vs. a project-wide effort I'm interested in at this time.
