### ISSUE TITLE
q1

### ISSUE THREAD

**Issue by heshamelgebaly** [capesstack/capes#95]
can i join Capes with existing Elk cluster, without installing kibana and logstash and elastic, and communicate with nodes  remotely, or the elk has to be installed in the Capes server ?

**Comment by peasead** [comment]
Great question, and of course! You can just update your Beats output config to point to your Elasticsearch instance
https://github.com/capesstack/capes/blob/3d18cc612dd4d165b7dd1288d0d175e699d5e8d8/beats/heartbeat.yml#L57
https://github.com/capesstack/capes/blob/3d18cc612dd4d165b7dd1288d0d175e699d5e8d8/beats/metricbeat.yml#L54

It should be noted, that the non-containerized version isn't being actively maintained. You should switch to the [containerized version](https://github.com/capesstack/capes-docker).

From there you'll just update the Docker commands to comment out installing Elasticsearch and Kibana and update the Beats Elasticsearch variable from `capes-elasticsearch-1` to your Elasticsearch instance.

https://github.com/capesstack/capes-docker/blob/7b31633c686b7008d783168027a51de9de70af02/deploy_capes.sh#L136

https://github.com/capesstack/capes-docker/blob/7b31633c686b7008d783168027a51de9de70af02/deploy_capes.sh#L139

**Comment by heshamelgebaly** [comment]
> Great question, and of course! You can just update your Beats output config to point to your Elasticsearch instance
> https://github.com/capesstack/capes/blob/3d18cc612dd4d165b7dd1288d0d175e699d5e8d8/beats/heartbeat.yml#L57
> 
> 
> https://github.com/capesstack/capes/blob/3d18cc612dd4d165b7dd1288d0d175e699d5e8d8/beats/metricbeat.yml#L54
> 
> It should be noted, that the non-containerized version isn't being actively maintained. You should switch to the [containerized version](https://github.com/capesstack/capes-docker).
> 
> From there you'll just update the Docker commands to comment out installing Elasticsearch and Kibana and update the Beats Elasticsearch variable from `capes-elasticsearch-1` to your Elasticsearch instance.
> 
> https://github.com/capesstack/capes-docker/blob/7b31633c686b7008d783168027a51de9de70af02/deploy_capes.sh#L136
> 
> https://github.com/capesstack/capes-docker/blob/7b31633c686b7008d783168027a51de9de70af02/deploy_capes.sh#L139

Thank you for ur answer
